/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_druid_processing_codecs_FastPFor_NativeFastPForCodec */

#ifndef _Included_org_apache_druid_processing_codecs_FastPFor_NativeFastPForCodec
#define _Included_org_apache_druid_processing_codecs_FastPFor_NativeFastPForCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_druid_processing_codecs_FastPFor_NativeFastPForCodec
 * Method:    loadCodec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_apache_druid_processing_codecs_FastPFor_NativeFastPForCodec_loadCodec
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_apache_druid_processing_codecs_FastPFor_NativeFastPForCodec
 * Method:    encode
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_druid_processing_codecs_FastPFor_NativeFastPForCodec_encode
  (JNIEnv *, jobject, jobject, jint, jobject, jint);

/*
 * Class:     org_apache_druid_processing_codecs_FastPFor_NativeFastPForCodec
 * Method:    decode
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_druid_processing_codecs_FastPFor_NativeFastPForCodec_decode
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jint);

/*
 * Class:     org_apache_druid_processing_codecs_FastPFor_NativeFastPForCodec
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_druid_processing_codecs_FastPFor_NativeFastPForCodec_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
